/**
 * Biome configuration registry.
 * Each biome sets the same CSS custom properties so weather/solar/seasonal
 * systems work without modification.
 */

const biomes = {
  /* ── Default (Pacific Northwest) ── */
  default: {
    key: 'default',
    name: 'Pacific Northwest',
    cssVariables: {
      '--biome-canopy':    '#3a7d44',
      '--biome-bg-far':    '#7a9a8a',
      '--biome-bg-mid':    '#4a7c59',
      '--biome-bg-near':   '#3a6b48',
      '--biome-fg-ground': '#2d5a3d',
      '--biome-trunk':     '#5c4033',
      '--biome-accent':    '#8fbc8f',
    },
    treeComponent: 'DefaultTrees',
    backgroundComponent: 'DefaultBackground',
    foregroundComponent: 'DefaultForeground',
    seasonalOverrides: {
      imbolc:  { '--biome-canopy': '#3a7044', '--biome-accent': '#a0c8a0' },
      ostara:  { '--biome-canopy': '#5eae5e', '--biome-accent': '#c8e6c8', '--seasonal-detail-opacity': '0.7' },
      beltane: { '--biome-canopy': '#4a9a4a', '--biome-accent': '#9ac89a' },
      litha:   { '--biome-canopy': '#2d6b34', '--seasonal-summer-detail-opacity': '0.6' },
      lammas:  { '--biome-canopy': '#4a8a3a', '--biome-accent': '#c8b040' },
      mabon:   { '--biome-canopy': '#b8860b', '--biome-accent': '#d4a030', '--seasonal-autumn-detail-opacity': '0.7' },
      samhain: { '--biome-canopy': '#2f5f3f', '--biome-accent': '#7a8a6a', '--seasonal-autumn-detail-opacity': '0.8', '--seasonal-atmosphere-tint': 'rgba(80,60,90,0.06)' },
      yule:    { '--biome-canopy': '#2f5f3f', '--biome-fg-ground': '#e8e8e8', '--seasonal-detail-opacity': '0.2' },
    },
    hasWater: false,
    groundCover: 'moss',
  },

  'pacific-northwest': {
    key: 'pacific-northwest',
    name: 'Pacific Northwest',
    cssVariables: {
      '--biome-canopy':    '#1f5c2e',
      '--biome-bg-far':    '#4a6a7a',
      '--biome-bg-mid':    '#1a4a2a',
      '--biome-bg-near':   '#2a5c3a',
      '--biome-fg-ground': '#1a3a1a',
      '--biome-trunk':     '#3a2a1a',
      '--biome-accent':    '#7a9a3a',
    },
    treeComponent: 'PNWMidground',
    backgroundComponent: 'PNWBackground',
    foregroundComponent: 'PNWForeground',
    seasonalOverrides: {
      imbolc:  { '--biome-accent': '#6a8a3a', '--seasonal-detail-opacity': '0.4' },
      ostara:  { '--biome-accent': '#5aae5a', '--seasonal-detail-opacity': '0.8', '--seasonal-spring-detail-opacity': '0.7' },
      beltane: { '--biome-canopy': '#1f6c2e', '--biome-accent': '#6aaa4a', '--seasonal-spring-detail-opacity': '0.5' },
      litha:   { '--biome-canopy': '#1a5a28', '--seasonal-summer-detail-opacity': '0.7' },
      lammas:  { '--biome-accent': '#8a8a2a' },
      mabon:   { '--biome-accent': '#d4a030', '--seasonal-autumn-detail-opacity': '0.7' },
      samhain: { '--seasonal-autumn-detail-opacity': '0.8', '--seasonal-atmosphere-tint': 'rgba(80,60,90,0.06)' },
      yule:    { '--biome-fg-ground': '#d8e0d8', '--seasonal-detail-opacity': '0.3' },
    },
    hasWater: true,
    groundCover: 'moss',
  },

  'british-isles': {
    key: 'british-isles',
    name: 'British Isles',
    cssVariables: {
      '--biome-canopy':    '#3a6a2a',
      '--biome-bg-far':    '#7a9a8a',
      '--biome-bg-mid':    '#4a7a4a',
      '--biome-bg-near':   '#2a5a2a',
      '--biome-fg-ground': '#2a4a1a',
      '--biome-trunk':     '#4a3a2a',
      '--biome-accent':    '#6a5a3a',
    },
    treeComponent: 'BritishIslesMidground',
    backgroundComponent: 'BritishIslesBackground',
    foregroundComponent: 'BritishIslesForeground',
    seasonalOverrides: {
      imbolc:  { '--biome-canopy': '#3a5a2a', '--biome-accent': '#7a6a4a' },
      ostara:  { '--biome-canopy': '#4a8a3a', '--seasonal-spring-detail-opacity': '0.8', '--biome-accent': '#6a5aaa' },
      beltane: { '--biome-canopy': '#3a7a2a', '--seasonal-spring-detail-opacity': '0.6' },
      litha:   { '--biome-canopy': '#2a6a1a', '--seasonal-summer-detail-opacity': '0.6' },
      lammas:  { '--biome-canopy': '#4a7a2a', '--biome-accent': '#9a8a3a' },
      mabon:   { '--seasonal-canopy': '#b87830', '--biome-accent': '#c89030', '--seasonal-autumn-detail-opacity': '0.7' },
      samhain: { '--seasonal-canopy': '#a06828', '--seasonal-autumn-detail-opacity': '0.5', '--seasonal-atmosphere-tint': 'rgba(80,60,90,0.08)' },
      yule:    { '--biome-fg-ground': '#d8dcd8', '--biome-canopy': '#5a4a3a', '--seasonal-spring-detail-opacity': '0' },
    },
    hasWater: false,
    groundCover: 'grass',
  },

  'mediterranean': {
    key: 'mediterranean',
    name: 'Mediterranean',
    cssVariables: {
      '--biome-canopy':    '#2a5a2a',
      '--biome-bg-far':    '#b09a5a',
      '--biome-bg-mid':    '#d4b47a',
      '--biome-bg-near':   '#c4a468',
      '--biome-fg-ground': '#8a7a5a',
      '--biome-trunk':     '#6a4a2a',
      '--biome-accent':    '#d4b47a',
    },
    treeComponent: 'MedMidground',
    backgroundComponent: 'MedBackground',
    foregroundComponent: 'MedForeground',
    seasonalOverrides: {
      imbolc:  { '--biome-canopy': '#2a5a2a' },
      ostara:  { '--biome-canopy': '#3a6a2a', '--seasonal-spring-detail-opacity': '0.6', '--seasonal-summer-detail-opacity': '0.4' },
      beltane: { '--biome-canopy': '#2a6a2a', '--seasonal-summer-detail-opacity': '0.6' },
      litha:   { '--biome-canopy': '#1a5a1a', '--seasonal-summer-detail-opacity': '0.8', '--biome-accent': '#d4a030' },
      lammas:  { '--biome-canopy': '#3a5a2a', '--biome-accent': '#c8a040', '--seasonal-summer-detail-opacity': '0.5' },
      mabon:   { '--biome-canopy': '#3a5a2a', '--biome-accent': '#c89830', '--seasonal-summer-detail-opacity': '0' },
      samhain: { '--biome-canopy': '#2a4a2a', '--seasonal-summer-detail-opacity': '0', '--seasonal-atmosphere-tint': 'rgba(80,60,90,0.05)' },
      yule:    { '--biome-canopy': '#2a4a2a', '--seasonal-summer-detail-opacity': '0', '--seasonal-citrus-opacity': '0.6' },
    },
    hasWater: true,
    groundCover: 'dry-scrub',
  },

  'nordic': {
    key: 'nordic',
    name: 'Nordic',
    cssVariables: {
      '--biome-canopy':    '#2a5a3a',
      '--biome-bg-far':    '#4a4a5a',
      '--biome-bg-mid':    '#3a4a5a',
      '--biome-bg-near':   '#2a3a2a',
      '--biome-fg-ground': '#3a3a2a',
      '--biome-trunk':     '#5a4a3a',
      '--biome-accent':    '#e8e0d0',
    },
    treeComponent: 'NordicMidground',
    backgroundComponent: 'NordicBackground',
    foregroundComponent: 'NordicForeground',
    seasonalOverrides: {
      imbolc:  { '--biome-fg-ground': '#c8d0d0', '--biome-canopy': '#2a4a3a' },
      ostara:  { '--biome-canopy': '#3a6a3a', '--biome-fg-ground': '#3a3a2a', '--seasonal-spring-detail-opacity': '0.5' },
      beltane: { '--biome-canopy': '#3a7a3a' },
      litha:   { '--biome-canopy': '#2a6a2a', '--seasonal-summer-detail-opacity': '0.7', '--seasonal-midnight-sun': '1' },
      lammas:  { '--biome-canopy': '#3a6a3a', '--biome-accent': '#d8d0b0' },
      mabon:   { '--biome-canopy': '#d4b43a', '--biome-accent': '#d4a020', '--seasonal-autumn-detail-opacity': '0.7' },
      samhain: { '--biome-canopy': '#8a6a2a', '--seasonal-autumn-detail-opacity': '0.5', '--seasonal-atmosphere-tint': 'rgba(80,60,90,0.08)' },
      yule:    { '--biome-canopy': '#1e3e2e', '--biome-fg-ground': '#e0e6e8', '--seasonal-snow-opacity': '0.9' },
    },
    hasWater: true,
    groundCover: 'moss',
  },

  'california-southwest': {
    key: 'california-southwest',
    name: 'California & Southwest',
    cssVariables: {
      '--biome-canopy':    '#7a9a5a',
      '--biome-bg-far':    '#d4c0a0',
      '--biome-bg-mid':    '#b0a078',
      '--biome-bg-near':   '#8a7a58',
      '--biome-fg-ground': '#b8a070',
      '--biome-trunk':     '#9a7a5a',
      '--biome-accent':    '#c4a43a',
    },
    treeComponent: 'CaliforniaSWMidground',
    backgroundComponent: 'CaliforniaSWBackground',
    foregroundComponent: 'CaliforniaSWForeground',
    seasonalOverrides: {
      imbolc:  { '--biome-canopy': '#6a8a4a' },
      ostara:  { '--biome-canopy': '#7aaa5a', '--seasonal-spring-detail-opacity': '0.5' },
      beltane: { '--biome-canopy': '#6a9a4a' },
      litha:   { '--biome-canopy': '#6a8a4a', '--biome-fg-ground': '#c8b080', '--seasonal-summer-detail-opacity': '0.8' },
      lammas:  { '--biome-canopy': '#7a8a4a', '--biome-accent': '#d4a030' },
      mabon:   { '--biome-canopy': '#8a8a3a', '--biome-accent': '#c89020' },
      samhain: { '--biome-canopy': '#6a7a3a', '--seasonal-atmosphere-tint': 'rgba(80,60,90,0.04)' },
      yule:    { '--biome-canopy': '#5a7a3a' },
    },
    hasWater: false,
    groundCover: 'dry-scrub',
  },

  'mountain-west': {
    key: 'mountain-west',
    name: 'Mountain West',
    cssVariables: {
      '--biome-canopy':    '#2a5a3a',
      '--biome-bg-far':    '#7a7a8a',
      '--biome-bg-mid':    '#5a5a4a',
      '--biome-bg-near':   '#3a5a3a',
      '--biome-fg-ground': '#4a6a3a',
      '--biome-trunk':     '#5a4030',
      '--biome-accent':    '#e8e0d0',
    },
    treeComponent: 'MountainWestMidground',
    backgroundComponent: 'MountainWestBackground',
    foregroundComponent: 'MountainWestForeground',
    seasonalOverrides: {
      imbolc:  { '--biome-fg-ground': '#b0c0b0' },
      ostara:  { '--biome-canopy': '#3a6a3a', '--seasonal-spring-detail-opacity': '0.7' },
      beltane: { '--biome-canopy': '#3a7a3a', '--seasonal-spring-detail-opacity': '0.8' },
      litha:   { '--biome-canopy': '#2a6a2a', '--seasonal-summer-detail-opacity': '0.7' },
      lammas:  { '--biome-canopy': '#4a6a2a', '--biome-accent': '#d8c080' },
      mabon:   { '--biome-canopy': '#d4a020', '--biome-accent': '#daa520', '--seasonal-autumn-detail-opacity': '0.7' },
      samhain: { '--biome-canopy': '#8a6a2a', '--seasonal-autumn-detail-opacity': '0.4', '--seasonal-atmosphere-tint': 'rgba(80,60,90,0.06)' },
      yule:    { '--biome-fg-ground': '#dce0e0', '--biome-canopy': '#1e3e2a', '--seasonal-snow-opacity': '0.7' },
    },
    hasWater: false,
    groundCover: 'grass',
  },

  'midwest': {
    key: 'midwest',
    name: 'Midwest',
    cssVariables: {
      '--biome-canopy':    '#5a8a4a',
      '--biome-bg-far':    '#d4b43a',
      '--biome-bg-mid':    '#7a9a68',
      '--biome-bg-near':   '#5a7a48',
      '--biome-fg-ground': '#4a6a38',
      '--biome-trunk':     '#6a5040',
      '--biome-accent':    '#c8b040',
    },
    treeComponent: 'MidwestMidground',
    backgroundComponent: 'MidwestBackground',
    foregroundComponent: 'MidwestForeground',
    seasonalOverrides: {
      imbolc:  { '--biome-fg-ground': '#b0c0a0', '--biome-canopy': '#4a6a3a' },
      ostara:  { '--biome-canopy': '#6aae5a', '--seasonal-spring-detail-opacity': '0.7' },
      beltane: { '--biome-canopy': '#5a9a4a', '--seasonal-spring-detail-opacity': '0.5' },
      litha:   { '--biome-canopy': '#4a8a2a', '--seasonal-summer-detail-opacity': '0.8', '--seasonal-firefly-opacity': '0.7' },
      lammas:  { '--biome-canopy': '#6a8a3a', '--biome-accent': '#d4a020', '--biome-bg-far': '#c8a028' },
      mabon:   { '--biome-canopy': '#c89020', '--biome-accent': '#d4a020', '--seasonal-autumn-detail-opacity': '0.7' },
      samhain: { '--biome-canopy': '#8a6a20', '--seasonal-autumn-detail-opacity': '0.4', '--seasonal-atmosphere-tint': 'rgba(80,60,90,0.06)' },
      yule:    { '--biome-fg-ground': '#d8dce0', '--biome-canopy': '#5a4a3a', '--seasonal-snow-opacity': '0.6' },
    },
    hasWater: false,
    groundCover: 'prairie',
  },

  'northeast': {
    key: 'northeast',
    name: 'Northeast',
    cssVariables: {
      '--biome-canopy':    '#3a7a3a',
      '--biome-bg-far':    '#8a9a8a',
      '--biome-bg-mid':    '#5a7a58',
      '--biome-bg-near':   '#4a6a46',
      '--biome-fg-ground': '#2a3a1a',
      '--biome-trunk':     '#5a4a3a',
      '--biome-accent':    '#8a7a5a',
    },
    treeComponent: 'NortheastMidground',
    backgroundComponent: 'NortheastBackground',
    foregroundComponent: 'NortheastForeground',
    seasonalOverrides: {
      imbolc:  { '--biome-canopy': '#4a6a3a', '--biome-fg-ground': '#c8d0c0' },
      ostara:  { '--biome-canopy': '#7aaa4a', '--seasonal-spring-detail-opacity': '0.7' },
      beltane: { '--biome-canopy': '#4a9a3a' },
      litha:   { '--biome-canopy': '#3a8a3a', '--seasonal-summer-detail-opacity': '0.6' },
      lammas:  { '--biome-canopy': '#5a8a3a', '--biome-accent': '#c8a040' },
      mabon:   { '--biome-canopy': '#d4843a', '--biome-accent': '#b04030', '--seasonal-autumn-detail-opacity': '0.85', '--seasonal-fallen-leaf-opacity': '0.7' },
      samhain: { '--biome-canopy': '#b04030', '--seasonal-autumn-detail-opacity': '0.6', '--seasonal-atmosphere-tint': 'rgba(80,60,90,0.08)' },
      yule:    { '--biome-fg-ground': '#dce0e4', '--biome-canopy': 'rgba(90,74,58,0.15)', '--seasonal-snow-opacity': '0.8', '--seasonal-branch-skeleton': '0.7' },
    },
    hasWater: false,
    groundCover: 'grass',
  },

  'southeast': {
    key: 'southeast',
    name: 'Southeast',
    cssVariables: {
      '--biome-canopy':    '#3a8a3a',
      '--biome-bg-far':    '#90a880',
      '--biome-bg-mid':    '#5a8a50',
      '--biome-bg-near':   '#3a7040',
      '--biome-fg-ground': '#2a5a28',
      '--biome-trunk':     '#6a5038',
      '--biome-accent':    '#7a8a6a',
    },
    treeComponent: 'SoutheastMidground',
    backgroundComponent: 'SoutheastBackground',
    foregroundComponent: 'SoutheastForeground',
    seasonalOverrides: {
      imbolc:  { '--biome-canopy': '#3a7a3a' },
      ostara:  { '--biome-canopy': '#4aae4a', '--seasonal-spring-detail-opacity': '0.6' },
      beltane: { '--biome-canopy': '#3a9a3a' },
      litha:   { '--biome-canopy': '#2a7a2a', '--seasonal-summer-detail-opacity': '0.8', '--seasonal-firefly-opacity': '0.7' },
      lammas:  { '--biome-canopy': '#3a8a2a', '--biome-accent': '#8a9a5a' },
      mabon:   { '--biome-canopy': '#5a8a3a', '--biome-accent': '#9a8a4a' },
      samhain: { '--biome-canopy': '#3a6a2a', '--seasonal-atmosphere-tint': 'rgba(80,60,90,0.06)' },
      yule:    { '--biome-canopy': '#2a5a2a' },
    },
    hasWater: true,
    groundCover: 'grass',
  },
};

export default biomes;

/**
 * Get a biome config by key, falling back to 'default'.
 * @param {string} key
 */
export function getBiomeConfig(key) {
  return biomes[key] || biomes.default;
}
