/**
 * creatures.js — Full creature roster for Under Pines.
 *
 * 71 creatures across 4 tiers: common, uncommon, rare, legendary.
 * Each creature is biome-locked and has scheduling/animation metadata.
 */

const FREQ = {
  common:    { minHours: 8,   maxHours: 16  },
  uncommon:  { minHours: 36,  maxHours: 72  },
  rare:      { minHours: 120, maxHours: 192 },
  legendary: { minHours: 288, maxHours: 504 },
};

const ALL_BIOMES = [
  'default', 'pacific-northwest', 'british-isles', 'nordic',
  'northeast', 'southeast', 'midwest', 'mountain-west',
  'california-southwest', 'mediterranean',
];

const US_BIOMES = ['pacific-northwest', 'northeast', 'southeast', 'midwest', 'mountain-west', 'california-southwest', 'default'];
const EURO_BIOMES = ['british-isles', 'nordic', 'mediterranean'];
const FOREST_BIOMES = ['pacific-northwest', 'northeast', 'british-isles', 'nordic', 'default'];
const WATER_BIOMES = ['pacific-northwest', 'nordic', 'southeast', 'mediterranean'];

export const creatures = [
  // ──────────────────────────────────────────────
  // COMMON — 20 creatures (appear 1–2× daily)
  // ──────────────────────────────────────────────
  {
    key: 'red-fox',
    name: 'Red Fox',
    type: 'animal',
    tier: 'common',
    biomes: ALL_BIOMES,
    activeHours: ['dawn', 'dusk', 'night'],
    weatherTrigger: null,
    seasonLock: null,
    frequency: FREQ.common,
    animationDuration: 12,
    movementStyle: 'trot',
  },
  {
    key: 'white-tailed-deer',
    name: 'White-Tailed Deer',
    type: 'animal',
    tier: 'common',
    biomes: ['northeast', 'southeast', 'midwest', 'default', 'pacific-northwest'],
    activeHours: ['dawn', 'dusk'],
    weatherTrigger: null,
    seasonLock: null,
    frequency: FREQ.common,
    animationDuration: 15,
    movementStyle: 'amble',
  },
  {
    key: 'raccoon',
    name: 'Raccoon',
    type: 'animal',
    tier: 'common',
    biomes: US_BIOMES,
    activeHours: ['dusk', 'night'],
    weatherTrigger: null,
    seasonLock: null,
    frequency: FREQ.common,
    animationDuration: 10,
    movementStyle: 'waddle',
  },
  {
    key: 'eastern-bluebird',
    name: 'Eastern Bluebird',
    type: 'animal',
    tier: 'common',
    biomes: ['northeast', 'southeast', 'midwest'],
    activeHours: ['morning', 'afternoon'],
    weatherTrigger: null,
    seasonLock: null,
    frequency: FREQ.common,
    animationDuration: 8,
    movementStyle: 'soar',
  },
  {
    key: 'gray-squirrel',
    name: 'Gray Squirrel',
    type: 'animal',
    tier: 'common',
    biomes: ['northeast', 'southeast', 'midwest', 'british-isles', 'default'],
    activeHours: ['morning', 'afternoon'],
    weatherTrigger: null,
    seasonLock: null,
    frequency: FREQ.common,
    animationDuration: 7,
    movementStyle: 'scurry',
  },
  {
    key: 'robin',
    name: 'Robin',
    type: 'animal',
    tier: 'common',
    biomes: ['northeast', 'british-isles', 'midwest', 'default'],
    activeHours: ['dawn', 'morning'],
    weatherTrigger: null,
    seasonLock: null,
    frequency: FREQ.common,
    animationDuration: 8,
    movementStyle: 'hop',
  },
  {
    key: 'chipmunk',
    name: 'Chipmunk',
    type: 'animal',
    tier: 'common',
    biomes: ['northeast', 'midwest', 'mountain-west', 'default'],
    activeHours: ['morning', 'afternoon'],
    weatherTrigger: null,
    seasonLock: null,
    frequency: FREQ.common,
    animationDuration: 6,
    movementStyle: 'scurry',
  },
  {
    key: 'rabbit',
    name: 'Cottontail Rabbit',
    type: 'animal',
    tier: 'common',
    biomes: ALL_BIOMES,
    activeHours: ['dawn', 'dusk'],
    weatherTrigger: null,
    seasonLock: null,
    frequency: FREQ.common,
    animationDuration: 10,
    movementStyle: 'hop',
  },
  {
    key: 'barn-swallow',
    name: 'Barn Swallow',
    type: 'animal',
    tier: 'common',
    biomes: ['midwest', 'southeast', 'california-southwest', 'mediterranean'],
    activeHours: ['morning', 'afternoon', 'dusk'],
    weatherTrigger: null,
    seasonLock: null,
    frequency: FREQ.common,
    animationDuration: 9,
    movementStyle: 'soar',
  },
  {
    key: 'tree-frog',
    name: 'Tree Frog',
    type: 'animal',
    tier: 'common',
    biomes: ['pacific-northwest', 'southeast', 'northeast', 'default'],
    activeHours: ['dusk', 'night'],
    weatherTrigger: 'rain',
    seasonLock: null,
    frequency: FREQ.common,
    animationDuration: 12,
    movementStyle: 'perch',
  },
  {
    key: 'crow',
    name: 'Crow',
    type: 'animal',
    tier: 'common',
    biomes: ALL_BIOMES,
    activeHours: ['morning', 'afternoon'],
    weatherTrigger: null,
    seasonLock: null,
    frequency: FREQ.common,
    animationDuration: 10,
    movementStyle: 'soar',
  },
  {
    key: 'hedgehog',
    name: 'Hedgehog',
    type: 'animal',
    tier: 'common',
    biomes: ['british-isles', 'nordic', 'mediterranean'],
    activeHours: ['dusk', 'night'],
    weatherTrigger: null,
    seasonLock: null,
    frequency: FREQ.common,
    animationDuration: 14,
    movementStyle: 'waddle',
  },
  {
    key: 'red-squirrel',
    name: 'Red Squirrel',
    type: 'animal',
    tier: 'common',
    biomes: ['british-isles', 'nordic'],
    activeHours: ['morning', 'afternoon'],
    weatherTrigger: null,
    seasonLock: null,
    frequency: FREQ.common,
    animationDuration: 7,
    movementStyle: 'scurry',
  },
  {
    key: 'wren',
    name: 'Wren',
    type: 'animal',
    tier: 'common',
    biomes: ['british-isles', 'northeast', 'default'],
    activeHours: ['dawn', 'morning'],
    weatherTrigger: null,
    seasonLock: null,
    frequency: FREQ.common,
    animationDuration: 6,
    movementStyle: 'hop',
  },
  {
    key: 'firefly',
    name: 'Firefly',
    type: 'animal',
    tier: 'common',
    biomes: ['southeast', 'midwest', 'northeast'],
    activeHours: ['dusk', 'night'],
    weatherTrigger: null,
    seasonLock: 'litha',
    frequency: FREQ.common,
    animationDuration: 20,
    movementStyle: 'drift',
  },
  {
    key: 'salamander',
    name: 'Salamander',
    type: 'animal',
    tier: 'common',
    biomes: ['pacific-northwest', 'northeast', 'southeast', 'default'],
    activeHours: ['dawn', 'dusk', 'night'],
    weatherTrigger: 'rain',
    seasonLock: null,
    frequency: FREQ.common,
    animationDuration: 14,
    movementStyle: 'creep',
  },
  {
    key: 'pika',
    name: 'Pika',
    type: 'animal',
    tier: 'common',
    biomes: ['mountain-west'],
    activeHours: ['morning', 'afternoon'],
    weatherTrigger: null,
    seasonLock: null,
    frequency: FREQ.common,
    animationDuration: 6,
    movementStyle: 'scurry',
  },
  {
    key: 'roadrunner',
    name: 'Roadrunner',
    type: 'animal',
    tier: 'common',
    biomes: ['california-southwest'],
    activeHours: ['morning', 'afternoon'],
    weatherTrigger: null,
    seasonLock: null,
    frequency: FREQ.common,
    animationDuration: 8,
    movementStyle: 'dash',
  },
  {
    key: 'gecko',
    name: 'Gecko',
    type: 'animal',
    tier: 'common',
    biomes: ['mediterranean', 'california-southwest'],
    activeHours: ['dusk', 'night'],
    weatherTrigger: null,
    seasonLock: null,
    frequency: FREQ.common,
    animationDuration: 10,
    movementStyle: 'creep',
  },
  {
    key: 'marmot',
    name: 'Marmot',
    type: 'animal',
    tier: 'common',
    biomes: ['mountain-west', 'nordic'],
    activeHours: ['morning', 'afternoon'],
    weatherTrigger: null,
    seasonLock: null,
    frequency: FREQ.common,
    animationDuration: 10,
    movementStyle: 'waddle',
  },

  // ──────────────────────────────────────────────
  // UNCOMMON — 20 creatures (every 2–3 days)
  // ──────────────────────────────────────────────
  {
    key: 'barn-owl',
    name: 'Barn Owl',
    type: 'animal',
    tier: 'uncommon',
    biomes: ALL_BIOMES,
    activeHours: ['dusk', 'night'],
    weatherTrigger: null,
    seasonLock: null,
    frequency: FREQ.uncommon,
    animationDuration: 12,
    movementStyle: 'soar',
  },
  {
    key: 'great-horned-owl',
    name: 'Great Horned Owl',
    type: 'animal',
    tier: 'uncommon',
    biomes: US_BIOMES,
    activeHours: ['dusk', 'night'],
    weatherTrigger: null,
    seasonLock: null,
    frequency: FREQ.uncommon,
    animationDuration: 14,
    movementStyle: 'perch',
  },
  {
    key: 'black-bear',
    name: 'Black Bear',
    type: 'animal',
    tier: 'uncommon',
    biomes: ['pacific-northwest', 'northeast', 'southeast', 'mountain-west', 'default'],
    activeHours: ['dawn', 'morning', 'dusk'],
    weatherTrigger: null,
    seasonLock: null,
    frequency: FREQ.uncommon,
    animationDuration: 18,
    movementStyle: 'amble',
  },
  {
    key: 'river-otter',
    name: 'River Otter',
    type: 'animal',
    tier: 'uncommon',
    biomes: ['pacific-northwest', 'northeast', 'southeast', 'nordic', 'default'],
    activeHours: ['morning', 'afternoon'],
    weatherTrigger: null,
    seasonLock: null,
    frequency: FREQ.uncommon,
    animationDuration: 12,
    movementStyle: 'swim',
  },
  {
    key: 'snowshoe-hare',
    name: 'Snowshoe Hare',
    type: 'animal',
    tier: 'uncommon',
    biomes: ['pacific-northwest', 'northeast', 'mountain-west', 'nordic', 'default'],
    activeHours: ['dawn', 'dusk'],
    weatherTrigger: null,
    seasonLock: null,
    frequency: FREQ.uncommon,
    animationDuration: 10,
    movementStyle: 'hop',
  },
  {
    key: 'bobcat',
    name: 'Bobcat',
    type: 'animal',
    tier: 'uncommon',
    biomes: ['pacific-northwest', 'northeast', 'southeast', 'california-southwest', 'mountain-west', 'default'],
    activeHours: ['dawn', 'dusk', 'night'],
    weatherTrigger: null,
    seasonLock: null,
    frequency: FREQ.uncommon,
    animationDuration: 12,
    movementStyle: 'creep',
  },
  {
    key: 'badger',
    name: 'Badger',
    type: 'animal',
    tier: 'uncommon',
    biomes: ['british-isles', 'nordic', 'midwest'],
    activeHours: ['dusk', 'night'],
    weatherTrigger: null,
    seasonLock: null,
    frequency: FREQ.uncommon,
    animationDuration: 14,
    movementStyle: 'waddle',
  },
  {
    key: 'red-deer',
    name: 'Red Deer',
    type: 'animal',
    tier: 'uncommon',
    biomes: ['british-isles', 'nordic', 'mediterranean'],
    activeHours: ['dawn', 'dusk'],
    weatherTrigger: null,
    seasonLock: null,
    frequency: FREQ.uncommon,
    animationDuration: 16,
    movementStyle: 'amble',
  },
  {
    key: 'heron',
    name: 'Great Blue Heron',
    type: 'animal',
    tier: 'uncommon',
    biomes: WATER_BIOMES,
    activeHours: ['dawn', 'morning', 'afternoon'],
    weatherTrigger: null,
    seasonLock: null,
    frequency: FREQ.uncommon,
    animationDuration: 18,
    movementStyle: 'wade',
  },
  {
    key: 'elk',
    name: 'Elk',
    type: 'animal',
    tier: 'uncommon',
    biomes: ['mountain-west', 'pacific-northwest', 'default'],
    activeHours: ['dawn', 'dusk'],
    weatherTrigger: null,
    seasonLock: null,
    frequency: FREQ.uncommon,
    animationDuration: 16,
    movementStyle: 'amble',
  },
  {
    key: 'coyote',
    name: 'Coyote',
    type: 'animal',
    tier: 'uncommon',
    biomes: US_BIOMES,
    activeHours: ['dusk', 'night'],
    weatherTrigger: null,
    seasonLock: null,
    frequency: FREQ.uncommon,
    animationDuration: 12,
    movementStyle: 'trot',
  },
  {
    key: 'beaver',
    name: 'Beaver',
    type: 'animal',
    tier: 'uncommon',
    biomes: ['pacific-northwest', 'northeast', 'midwest', 'default'],
    activeHours: ['dusk', 'night'],
    weatherTrigger: null,
    seasonLock: null,
    frequency: FREQ.uncommon,
    animationDuration: 14,
    movementStyle: 'swim',
  },
  {
    key: 'pine-marten',
    name: 'Pine Marten',
    type: 'animal',
    tier: 'uncommon',
    biomes: ['british-isles', 'nordic', 'pacific-northwest'],
    activeHours: ['dawn', 'dusk'],
    weatherTrigger: null,
    seasonLock: null,
    frequency: FREQ.uncommon,
    animationDuration: 10,
    movementStyle: 'scurry',
  },
  {
    key: 'wild-boar',
    name: 'Wild Boar',
    type: 'animal',
    tier: 'uncommon',
    biomes: ['mediterranean', 'british-isles', 'nordic'],
    activeHours: ['dusk', 'night'],
    weatherTrigger: null,
    seasonLock: null,
    frequency: FREQ.uncommon,
    animationDuration: 14,
    movementStyle: 'trot',
  },
  {
    key: 'armadillo',
    name: 'Armadillo',
    type: 'animal',
    tier: 'uncommon',
    biomes: ['southeast', 'california-southwest'],
    activeHours: ['dusk', 'night'],
    weatherTrigger: null,
    seasonLock: null,
    frequency: FREQ.uncommon,
    animationDuration: 14,
    movementStyle: 'waddle',
  },
  {
    key: 'red-tailed-hawk',
    name: 'Red-Tailed Hawk',
    type: 'animal',
    tier: 'uncommon',
    biomes: US_BIOMES,
    activeHours: ['morning', 'afternoon'],
    weatherTrigger: null,
    seasonLock: null,
    frequency: FREQ.uncommon,
    animationDuration: 14,
    movementStyle: 'soar',
  },
  {
    key: 'tortoise',
    name: 'Desert Tortoise',
    type: 'animal',
    tier: 'uncommon',
    biomes: ['california-southwest', 'mediterranean'],
    activeHours: ['morning', 'afternoon'],
    weatherTrigger: null,
    seasonLock: null,
    frequency: FREQ.uncommon,
    animationDuration: 20,
    movementStyle: 'creep',
  },
  {
    key: 'porcupine',
    name: 'Porcupine',
    type: 'animal',
    tier: 'uncommon',
    biomes: ['pacific-northwest', 'northeast', 'mountain-west', 'default'],
    activeHours: ['dusk', 'night'],
    weatherTrigger: null,
    seasonLock: null,
    frequency: FREQ.uncommon,
    animationDuration: 16,
    movementStyle: 'waddle',
  },
  {
    key: 'kingfisher',
    name: 'Kingfisher',
    type: 'animal',
    tier: 'uncommon',
    biomes: ['british-isles', 'nordic', 'mediterranean'],
    activeHours: ['morning', 'afternoon'],
    weatherTrigger: null,
    seasonLock: null,
    frequency: FREQ.uncommon,
    animationDuration: 8,
    movementStyle: 'soar',
  },
  {
    key: 'alligator',
    name: 'Alligator',
    type: 'animal',
    tier: 'uncommon',
    biomes: ['southeast'],
    activeHours: ['morning', 'afternoon', 'dusk'],
    weatherTrigger: null,
    seasonLock: null,
    frequency: FREQ.uncommon,
    animationDuration: 20,
    movementStyle: 'swim',
  },

  // ──────────────────────────────────────────────
  // RARE — 16 creatures (roughly weekly)
  // ──────────────────────────────────────────────
  {
    key: 'gray-wolf',
    name: 'Gray Wolf',
    type: 'animal',
    tier: 'rare',
    biomes: ['pacific-northwest', 'mountain-west', 'nordic', 'default'],
    activeHours: ['dawn', 'dusk', 'night'],
    weatherTrigger: null,
    seasonLock: null,
    frequency: FREQ.rare,
    animationDuration: 14,
    movementStyle: 'trot',
  },
  {
    key: 'moose',
    name: 'Moose',
    type: 'animal',
    tier: 'rare',
    biomes: ['pacific-northwest', 'northeast', 'mountain-west', 'nordic', 'default'],
    activeHours: ['dawn', 'morning', 'dusk'],
    weatherTrigger: null,
    seasonLock: null,
    frequency: FREQ.rare,
    animationDuration: 20,
    movementStyle: 'amble',
  },
  {
    key: 'mountain-lion',
    name: 'Mountain Lion',
    type: 'animal',
    tier: 'rare',
    biomes: ['mountain-west', 'california-southwest', 'pacific-northwest', 'default'],
    activeHours: ['dawn', 'dusk', 'night'],
    weatherTrigger: null,
    seasonLock: null,
    frequency: FREQ.rare,
    animationDuration: 12,
    movementStyle: 'creep',
  },
  {
    key: 'bald-eagle',
    name: 'Bald Eagle',
    type: 'animal',
    tier: 'rare',
    biomes: ['pacific-northwest', 'northeast', 'mountain-west', 'midwest', 'default'],
    activeHours: ['morning', 'afternoon'],
    weatherTrigger: null,
    seasonLock: null,
    frequency: FREQ.rare,
    animationDuration: 16,
    movementStyle: 'soar',
  },
  {
    key: 'wolverine',
    name: 'Wolverine',
    type: 'animal',
    tier: 'rare',
    biomes: ['mountain-west', 'nordic', 'pacific-northwest'],
    activeHours: ['dawn', 'dusk', 'night'],
    weatherTrigger: null,
    seasonLock: null,
    frequency: FREQ.rare,
    animationDuration: 10,
    movementStyle: 'trot',
  },
  {
    key: 'lynx',
    name: 'Lynx',
    type: 'animal',
    tier: 'rare',
    biomes: ['nordic', 'mountain-west'],
    activeHours: ['dawn', 'dusk', 'night'],
    weatherTrigger: null,
    seasonLock: null,
    frequency: FREQ.rare,
    animationDuration: 12,
    movementStyle: 'creep',
  },
  {
    key: 'golden-eagle',
    name: 'Golden Eagle',
    type: 'animal',
    tier: 'rare',
    biomes: ['mountain-west', 'california-southwest', 'mediterranean', 'british-isles'],
    activeHours: ['morning', 'afternoon'],
    weatherTrigger: null,
    seasonLock: null,
    frequency: FREQ.rare,
    animationDuration: 16,
    movementStyle: 'soar',
  },
  {
    key: 'snowy-owl',
    name: 'Snowy Owl',
    type: 'animal',
    tier: 'rare',
    biomes: ['nordic', 'northeast', 'mountain-west'],
    activeHours: ['dawn', 'morning', 'afternoon', 'dusk'],
    weatherTrigger: 'snow',
    seasonLock: null,
    frequency: FREQ.rare,
    animationDuration: 14,
    movementStyle: 'soar',
  },
  {
    key: 'iberian-lynx',
    name: 'Iberian Lynx',
    type: 'animal',
    tier: 'rare',
    biomes: ['mediterranean'],
    activeHours: ['dawn', 'dusk'],
    weatherTrigger: null,
    seasonLock: null,
    frequency: FREQ.rare,
    animationDuration: 12,
    movementStyle: 'creep',
  },
  {
    key: 'peregrine-falcon',
    name: 'Peregrine Falcon',
    type: 'animal',
    tier: 'rare',
    biomes: ALL_BIOMES,
    activeHours: ['morning', 'afternoon'],
    weatherTrigger: null,
    seasonLock: null,
    frequency: FREQ.rare,
    animationDuration: 8,
    movementStyle: 'soar',
  },
  {
    key: 'black-dog',
    name: 'Black Dog',
    type: 'mythical',
    tier: 'rare',
    biomes: ['british-isles', 'northeast'],
    activeHours: ['night'],
    weatherTrigger: 'fog',
    seasonLock: null,
    frequency: FREQ.rare,
    animationDuration: 14,
    movementStyle: 'trot',
  },
  {
    key: 'will-o-the-wisp',
    name: "Will-o'-the-Wisp",
    type: 'mythical',
    tier: 'rare',
    biomes: ['british-isles', 'nordic', 'southeast', 'northeast'],
    activeHours: ['night'],
    weatherTrigger: 'fog',
    seasonLock: null,
    frequency: FREQ.rare,
    animationDuration: 18,
    movementStyle: 'drift',
  },
  {
    key: 'jackalope',
    name: 'Jackalope',
    type: 'mythical',
    tier: 'rare',
    biomes: ['mountain-west', 'midwest', 'california-southwest'],
    activeHours: ['dawn', 'dusk'],
    weatherTrigger: null,
    seasonLock: null,
    frequency: FREQ.rare,
    animationDuration: 8,
    movementStyle: 'hop',
  },
  {
    key: 'puckwudgie',
    name: 'Puckwudgie',
    type: 'mythical',
    tier: 'rare',
    biomes: ['northeast'],
    activeHours: ['dusk', 'night'],
    weatherTrigger: null,
    seasonLock: null,
    frequency: FREQ.rare,
    animationDuration: 10,
    movementStyle: 'creep',
  },
  {
    key: 'ghost',
    name: 'Ghost',
    type: 'mythical',
    tier: 'rare',
    biomes: ALL_BIOMES,
    activeHours: ['night'],
    weatherTrigger: null,
    seasonLock: 'samhain',
    frequency: FREQ.rare,
    animationDuration: 16,
    movementStyle: 'drift',
  },
  {
    key: 'witch',
    name: 'Witch',
    type: 'mythical',
    tier: 'rare',
    biomes: ALL_BIOMES,
    activeHours: ['dusk', 'night'],
    weatherTrigger: null,
    seasonLock: 'samhain',
    frequency: FREQ.rare,
    animationDuration: 14,
    movementStyle: 'soar',
  },

  // ──────────────────────────────────────────────
  // LEGENDARY — 15 creatures (every 2–3 weeks)
  // ──────────────────────────────────────────────
  {
    key: 'sasquatch',
    name: 'Sasquatch',
    type: 'mythical',
    tier: 'legendary',
    biomes: ['pacific-northwest', 'mountain-west', 'default'],
    activeHours: ['dusk', 'night'],
    weatherTrigger: null,
    seasonLock: null,
    frequency: FREQ.legendary,
    animationDuration: 18,
    movementStyle: 'amble',
  },
  {
    key: 'loch-ness-monster',
    name: 'Loch Ness Monster',
    type: 'mythical',
    tier: 'legendary',
    biomes: ['british-isles', 'nordic'],
    activeHours: ['dawn', 'morning', 'dusk'],
    weatherTrigger: 'fog',
    seasonLock: null,
    frequency: FREQ.legendary,
    animationDuration: 20,
    movementStyle: 'swim',
  },
  {
    key: 'banshee',
    name: 'Banshee',
    type: 'mythical',
    tier: 'legendary',
    biomes: ['british-isles'],
    activeHours: ['night'],
    weatherTrigger: null,
    seasonLock: 'samhain',
    frequency: FREQ.legendary,
    animationDuration: 16,
    movementStyle: 'drift',
  },
  {
    key: 'mothman',
    name: 'Mothman',
    type: 'mythical',
    tier: 'legendary',
    biomes: ['northeast', 'southeast', 'midwest'],
    activeHours: ['night'],
    weatherTrigger: 'thunderstorm',
    seasonLock: null,
    frequency: FREQ.legendary,
    animationDuration: 14,
    movementStyle: 'hover',
  },
  {
    key: 'wendigo',
    name: 'Wendigo',
    type: 'mythical',
    tier: 'legendary',
    biomes: ['northeast', 'nordic', 'mountain-west'],
    activeHours: ['night'],
    weatherTrigger: 'snow',
    seasonLock: 'yule',
    frequency: FREQ.legendary,
    animationDuration: 16,
    movementStyle: 'creep',
  },
  {
    key: 'selkie',
    name: 'Selkie',
    type: 'mythical',
    tier: 'legendary',
    biomes: ['british-isles', 'nordic'],
    activeHours: ['dawn', 'dusk'],
    weatherTrigger: null,
    seasonLock: null,
    frequency: FREQ.legendary,
    animationDuration: 18,
    movementStyle: 'swim',
  },
  {
    key: 'thunderbird',
    name: 'Thunderbird',
    type: 'mythical',
    tier: 'legendary',
    biomes: ['pacific-northwest', 'mountain-west', 'midwest', 'default'],
    activeHours: ['afternoon', 'dusk'],
    weatherTrigger: 'thunderstorm',
    seasonLock: null,
    frequency: FREQ.legendary,
    animationDuration: 16,
    movementStyle: 'soar',
  },
  {
    key: 'headless-horseman',
    name: 'Headless Horseman',
    type: 'mythical',
    tier: 'legendary',
    biomes: ['northeast'],
    activeHours: ['night'],
    weatherTrigger: 'fog',
    seasonLock: 'mabon',
    frequency: FREQ.legendary,
    animationDuration: 14,
    movementStyle: 'gallop',
  },
  {
    key: 'jersey-devil',
    name: 'Jersey Devil',
    type: 'mythical',
    tier: 'legendary',
    biomes: ['northeast', 'southeast'],
    activeHours: ['night'],
    weatherTrigger: null,
    seasonLock: null,
    frequency: FREQ.legendary,
    animationDuration: 12,
    movementStyle: 'hover',
  },
  {
    key: 'skinwalker',
    name: 'Skinwalker',
    type: 'mythical',
    tier: 'legendary',
    biomes: ['california-southwest', 'mountain-west'],
    activeHours: ['night'],
    weatherTrigger: null,
    seasonLock: null,
    frequency: FREQ.legendary,
    animationDuration: 14,
    movementStyle: 'creep',
  },
  {
    key: 'kelpie',
    name: 'Kelpie',
    type: 'mythical',
    tier: 'legendary',
    biomes: ['british-isles', 'nordic'],
    activeHours: ['dusk', 'night'],
    weatherTrigger: 'rain',
    seasonLock: null,
    frequency: FREQ.legendary,
    animationDuration: 18,
    movementStyle: 'swim',
  },
  {
    key: 'chupacabra',
    name: 'Chupacabra',
    type: 'mythical',
    tier: 'legendary',
    biomes: ['california-southwest', 'southeast'],
    activeHours: ['night'],
    weatherTrigger: null,
    seasonLock: null,
    frequency: FREQ.legendary,
    animationDuration: 10,
    movementStyle: 'creep',
  },
  {
    key: 'frost-giant',
    name: 'Frost Giant',
    type: 'mythical',
    tier: 'legendary',
    biomes: ['nordic', 'mountain-west'],
    activeHours: ['night'],
    weatherTrigger: 'snow',
    seasonLock: 'yule',
    frequency: FREQ.legendary,
    animationDuration: 22,
    movementStyle: 'amble',
  },
  {
    key: 'rougarou',
    name: 'Rougarou',
    type: 'mythical',
    tier: 'legendary',
    biomes: ['southeast'],
    activeHours: ['night'],
    weatherTrigger: 'fog',
    seasonLock: null,
    frequency: FREQ.legendary,
    animationDuration: 14,
    movementStyle: 'creep',
  },
  {
    key: 'phoenix',
    name: 'Phoenix',
    type: 'mythical',
    tier: 'legendary',
    biomes: ['mediterranean', 'california-southwest'],
    activeHours: ['dawn', 'dusk'],
    weatherTrigger: null,
    seasonLock: 'litha',
    frequency: FREQ.legendary,
    animationDuration: 16,
    movementStyle: 'soar',
  },
];

/** Lookup map by key */
export const creatureMap = Object.fromEntries(creatures.map(c => [c.key, c]));

/** Get creatures filtered by tier */
export function getCreaturesByTier(tier) {
  return creatures.filter(c => c.tier === tier);
}

/** Get creatures available in a given biome */
export function getCreaturesForBiome(biomeKey) {
  return creatures.filter(c => c.biomes.includes(biomeKey));
}

export default creatures;
